
version: '2'

services:
  mysql:
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=desenv
      -  MYSQL_DATABASE=x6_corretora  
    ports:
     - "3306:3306"
    networks:
      rede:
        ipv4_address: 10.5.0.5

networks:
  rede:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1